### ISSUE TITLE
build out data model for various poker types

### ISSUE THREAD

**Issue by raynjamin** [TIY-Charlotte-Java/TheGame#3]
We need:

Card
- Suite (possibly enum)
- A value (between 2 and A)
- Static build fresh deck method.

Game
- Deck of cards
- Shuffle remaining cards (no card counting here bucko!)
- List of Users
- Methods to perform game-based actions

User
- Name
- Chip Count

**Comment by zombieApoc** [comment]
basic with room for improvement
